name: Build Nikola Site

on:
  push:
    branches:
      - src  # Change this to your main branch

jobs:
  deploy-nikola-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
          with:
            python-version: 3.10  # Change this to your desired Python version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -U "Nikola[extras]"
      - name: Build Nikola Site
        run: nikola build
      - name: Uploading output to S3
        run: aws s3 sync ./output/ s3://edgarl-website --delete